version: "3.7"
services:
  library-postgresql:
    image: postgres:16.4
    container_name: library-postgresql
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library-fellipe
      POSTGRES_PASSWORD: library77
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    networks:
      - library-network


networks:
  library-network:
    driver: bridge

